---
title: "Projeto I"
author: 
  - "Bárbara"
  - "Nathalia Gabriella Ferreira dos Santos"
date: "`r Sys.Date()`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Pacotes

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
```

# Análises

## Saneamento de dados

### **Extraindo dados**

Colunas usadas: Dados Atuais, *Dados Gestacionais*, *ELISAs*, *Imunoturbidimetria*,*Doenças Crônicas*

```{r}
rm(list = ls()) # limpa enviroment

df1 <- read_xlsx("dados.xlsx", sheet = "Dados Atuais")
df2 <- read_xlsx("dados.xlsx", sheet = "Dados Gestacionais")
df3 <- read_xlsx("dados.xlsx", sheet = "ELISAs")
df4 <- read_xlsx("dados.xlsx", sheet = "Imunoturbidimetria")
df5 <- read_xlsx("dados.xlsx", sheet = "Doenças Crônicas")
```

-   DF1: Dados Atuais

```{r}
#df1 %>% colnames()
colunas_interesse <- c(
  "GRUPO      MN:0      MP:1", 
  "IDADE    anos",
  "ESCOLARIDADE COMPLETA  0: 4ª série completa   1:fundamental completo 2:médio completo 3:ensino técnico completo 4:superior completo 5:pós-graduação completa",
  "NÚMERO GESTAÇÕES",
  "Peso (kg)",
  "IMC",
  "GORDURA (%)",
  "PRESSÃO SISTÓLICA (mmHg)",
  "PRESSÃO DIASTÓLICA (mmHg)",
  "PRESSÃO ARTERIAL MÉDIA",
  "CINTURA (cm)",
  "ABDÔMEN (cm)",
  "QUADRIL (cm)",
  "RELAÇÃO CINTURA/QUADRIL",
  "NEU (10³/µL)",
  "LYM (10³/µL)",
  "NLR",
  "Colesterol total (mg/dL)",
  "HDL (mg/dL)",
  "LDL (mg/dL) DOSADO",
  "VLDL (mg/dL)",
  "Não-HDL (mg/dL)",
  "Triglicérides (mg/dL)",
  "HbA1c (%)",
  "Creatinina (mg/dL)",
  "Ritmo de filtrção glomerular calculado",
  "TGP/ALT",
  "TGO/AST",
  "Ácido Úrico",
  "CK",
  "Gama GT"
  )

renomear_colunas <- c(
  "grupo", 
  "idade",
  "escolaridade",
  "num_gestacoes",
  "peso",
  "imc",
  "gordura",  
  "pressao_sis",
  "pressao_dias",
  "pressao_media", 
  "cintura",
  "abdomen",
  "quadril",
  "cintura_quadril",
  "neu",
  "lym",
  "nlr",
  "colesterol_total",
  "hdl",
  "ldl_dosado",
  "vldl",
  "nao_hdl",
  "triglicerides",
  "hba1c",
  "creatinina",
  "filtr_glomerular",
  "tgp_alt",
  "tgo_ast",
  "acido_urico",
  "ck",
  "gama_gt"
  )


df1 <- df1 %>% select(all_of(colunas_interesse))
colnames(df1) <- renomear_colunas
```

```{r}
coluna_na_numerica <- function(lista, caracter = ".", substituto = ""){
  lista %>% 
    str_replace(. , pattern = ",", replacement = ".") %>%
    str_replace_na(. , replacement = "") %>% 
    ifelse(. == caracter, substituto, .) %>% as.numeric()
}

coluna_numerica <- function(lista){
  lista %>% 
    ifelse(. == 99999, NA, .) %>% as.numeric()
}
```

```{r}
grupos_nulos <- df1 %>% select(grupo) %>% is.na()
df1 <- df1 %>% 
  filter(! grupos_nulos) %>% 
  mutate(
    grupo = as.factor(grupo),
    escolaridade = as.factor(escolaridade),
    peso = coluna_numerica(idade),
    imc = coluna_na_numerica(imc, "#DIV/0!", NA) %>% coluna_numerica(),
    gordura = coluna_numerica(gordura),
    pressao_sis = coluna_numerica(pressao_sis),
    pressao_dias = coluna_numerica(pressao_dias),
    pressao_media = coluna_numerica(pressao_media),
    cintura = coluna_numerica(cintura),
    abdomen = coluna_numerica(abdomen),
    quadril = coluna_numerica(quadril),
    cintura_quadril = coluna_na_numerica(cintura_quadril, "#DIV/0!", NA) %>% coluna_numerica(),
    nlr = coluna_na_numerica(nlr, "#DIV/0!", NA) %>% coluna_numerica(),
    ldl_dosado = coluna_na_numerica(ldl_dosado, "#DIV/0!", NA) %>% coluna_numerica(),
    vldl = coluna_na_numerica(vldl, "#DIV/0!", NA) %>% coluna_numerica(),
    hba1c = coluna_numerica(hba1c),
    creatinina = coluna_numerica(creatinina),
    filtr_glomerular = coluna_na_numerica(filtr_glomerular, "#DIV/0!", NA) %>% coluna_numerica(),
    ck = coluna_numerica(ck)
    )
```

```{r}
df1 %>% summary()
```

-   DF2: Dados Gestacionais

```{r}
#df2 %>% colnames()
colunas_interesse <- c(
  "GRUPO      MN:0      MP:1",
  "Há quantos anos",
  "PESO BEBÊ (kg)",
  "PARTO                                     0:normal   1:cesariana   2:fórceps  3: induzido",
  "PARTO PREMATURO 0:não      1:sim"
  )

renomear_colunas <- c(
  "grupo",
  "quantos_anos_evento",
  "peso_bebe",
  "tipo_parto",
  "prematuro"
  )


df2 <- df2 %>% select(all_of(colunas_interesse))
colnames(df2) <- renomear_colunas
```

```{r}
grupos_nulos <- df2 %>% select(grupo) %>% is.na()
df2 <- df2 %>% 
  filter(! grupos_nulos) %>% 
  mutate(
    grupo = as.factor(grupo),
    quantos_anos_evento = quantos_anos_evento %>% as.numeric(),
    peso_bebe = coluna_numerica(peso_bebe),
    tipo_parto = as.factor(coluna_numerica(tipo_parto)),
    prematuro = as.factor(prematuro)
    )
```

```{r}
df2 %>% summary()
```

# Testes da curva

```{r}
#rm(list = ls()) # limpa enviroment
```

-   Curva com base nos dados

```{r}
df_1 <- read_xlsx("dados_amostrais.xlsx")

df_1 <- df_1 %>% select(x,y)

plot(df_1$y, log(df_1$x))

df_1$y %>% log() %>% hist()

fit1 <- lm(log(x) ~ y, data = df_1)
fit1 %>% summary()

reglin::ggresiduals(fit1)

plot(fit1)

newdata <- data.frame(y = c(0.166, 0.048, .152, 0.210, .207))

newdata$amostra <- predict(fit1, newdata) %>% exp()
```

-   Curva com base teórica

```{r}
df_2 <- read_xlsx("dados_teoricos.xlsx")

plot(df_2$y, df_2$x)

fit2 <- lm(x ~ y, data = df_2)
fit2 %>% summary()

reglin::ggresiduals(fit2)

plot(fit2)

newdata$teorico <- predict(fit2, newdata)
```

## Resultado curvas

```{r}
newdata
```

** Curva teorica vs amostral

```{r}
eq1 <- function(x){
  y = 0.1532 + ( (0.8722 - 0.1532) / (1 + (x/606.3139)^(-1.3109) ) )
  return(y)
}

eq2 <- function(x){
  y = 0.1173 + ( (0.202658 - 0.1173) / (1 + (x/10746.6371)^(-1.2605) ) )
  return(y)
}


teste = tibble(x = seq(0.1,1500,0.5),
               y = eq1(x)
)

teste2 = tibble(x = seq(0.1,1500,0.5),
                y = eq2(x)
)

bind_rows(teste %>% mutate(tipo = 'amostral'),
          teste2 %>% mutate(tipo = 'teorico')) %>% 
  ggplot(aes(x = x, y = y, color = tipo)) +
  geom_line(aes(group = tipo))


g1 <- ggplot(data = teste, aes(x = x, y = y)) +
  geom_line(group = 1) + 
  geom_point() +
  theme_minimal() + 
  labs(title = "Amostral")

g2 <- ggplot(data = teste2, aes(x = x, y = y)) +
  geom_line(group = 1) + 
  geom_point() +
  theme_minimal() + 
  labs(title = "Teórico")

gridExtra::grid.arrange(g1, g2, ncol = 2)

# fazer a inversa das eq e dps buscar os x em y
eq1(0.048)
eq2(0.048)

```
